name = "anvil/cip68-mint"
version = "0.0.3"
compiler = "v1.1.10"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'anvil/cip68-mint'"

[repository]
user = "anvil"
project = "cip68-mint"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
