name = "anvil-api-examples/hello-world"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'anvil-api-examples/hello-world'"

[repository]
user = "anvil-api-examples"
project = "hello-world"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
